"""Add usage_aggregations table

Revision ID: 38a6ddb6d637
Revises: d6c6fae8b8c8
Create Date: 2026-08-31 00:03:02.409228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38a6ddb6d637'
down_revision: Union[str, None] = 'd6c6fae8b8c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_aggregations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('api_calls', sa.BigInteger(), nullable=True),
    sa.Column('ai_tokens', sa.BigInteger(), nullable=True),
    sa.Column('api_cost_cents', sa.BigInteger(), nullable=True),
    sa.Column('token_cost_cents', sa.BigInteger(), nullable=True),
    sa.Column('total_cost_cents', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'period', name='uq_tenant_period')
    )
    op.create_index(op.f('ix_usage_aggregations_id'), 'usage_aggregations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_aggregations_id'), table_name='usage_aggregations')
    op.drop_table('usage_aggregations')
    # ### end Alembic commands ###
