"""Add unique constraint for idempotency_key per tenant

Revision ID: 41f67049cd88
Revises: 5ef412dafb98
Create Date: 2026-08-30 23:01:12.022897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41f67049cd88'
down_revision: Union[str, None] = '5ef412dafb98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_tenant_idempotency', 'usage_events', ['tenant_id', 'idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_tenant_idempotency', 'usage_events', type_='unique')
    # ### end Alembic commands ###
