"""Add unique constraint for idempotency_key per tenant

Revision ID: 5ef412dafb98
Revises: bf71bb8a242b
Create Date: 2026-08-30 23:00:34.217170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ef412dafb98'
down_revision: Union[str, None] = 'bf71bb8a242b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
