"""Initial migration - create tenants, plans, subscriptions, usage_events

Revision ID: bf71bb8a242b
Revises: 46c529e9b774
Create Date: 2026-08-30 19:58:24.308820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf71bb8a242b'
down_revision: Union[str, None] = '46c529e9b774'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
